name: ci

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install deps
        run: pnpm install
      - name: Run typecheck
        run: pnpm run typecheck
      - name: Run lint
        run: pnpm run lint
